%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/mm/works/work_matlab/work_ANN_ml/work_ANN_XP_ser/m_files/atom_rel.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2014/05/21 19:57:05

%% Initialize variables.
filename = '/home/mm/works/work_matlab/work_ANN_ml/work_ANN_XP_ser/m_files/atom_rel.txt';
delimiter = ' ';

%% Format string for each line of text:
%   column1: double (%f)
%	column2: text (%s)
%   column3: double (%f)
%	column4: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%s%f%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
dataArray([1, 3]) = cellfun(@(x) num2cell(x), dataArray([1, 3]), 'UniformOutput', false);
atomrel1 = [dataArray{1:end-1}];
%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;

save Mat_atom_pair.mat atomrel


%% logs
% mod : 21-May-2014 19:57:57
% mod the atom pair pattern.

% mod : 21-May-2014 19:28:38
%